# Generated by Django 3.0.8 on 2020-07-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Middle_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Company_name', models.CharField(max_length=100)),
                ('Mobile_Number', models.IntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('Date_of_Birth', models.DateField(max_length=100)),
                ('Pin_Code', models.IntegerField()),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Adhaar_Card', models.ImageField(upload_to='pics')),
                ('Pan_Card', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
